package atividades;

import java.util.Scanner;

public class atividade1 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		Scanner sc = new Scanner(System.in);
		System.out.print("Digite o seu código: ");
		String codigo1 = sc.next();
		System.out.print("Digite o seu nome: ");
		String nome1 = sc.next();
		System.out.print("Digite seu sexo: ");
		String sexo1 = sc.next();
		System.out.print("Digite sua data de nascimento: ");
		String data1 = sc.next();
		System.out.print("Digite seu e-mail: ");
		String email1 = sc.next();
		System.out.print("Digite seu telefone/celular: ");
		String cel1 = sc.next();
		System.out.print("Digite seu CPF: ");
		String cpf1 = sc.next();
		System.out.print("Digite seu endereço: ");
		String endereco1 = sc.next();
		System.out.println("");
		System.out.print("Digite o seu código: ");
		String codigo2 = sc.next();
		System.out.print("Digite o seu nome: ");
		String nome2 = sc.next();
		System.out.print("Digite seu sexo: ");
		String sexo2 = sc.next();
		System.out.print("Digite sua data de nascimento: ");
		String data2 = sc.next();
		System.out.print("Digite seu e-mail: ");
		String email2 = sc.next();
		System.out.print("Digite seu telefone/celular: ");
		String cel2 = sc.next();
		System.out.print("Digite seu CPF: ");
		String cpf2 = sc.next();
		System.out.print("Digite seu endereço: ");
		String endereco2 = sc.next();
		System.out.println("");
		System.out.print("Digite o seu código: ");
		String codigo3 = sc.next();
		System.out.print("Digite o seu nome: ");
		String nome3 = sc.next();
		System.out.print("Digite seu sexo: ");
		String sexo3 = sc.next();
		System.out.print("Digite sua data de nascimento: ");
		String data3 = sc.next();
		System.out.print("Digite seu e-mail: ");
		String email3 = sc.next();
		System.out.print("Digite seu telefone/celular: ");
		String cel3 = sc.next();
		System.out.print("Digite seu CPF: ");
		String cpf3 = sc.next();
		System.out.print("Digite seu endereço: ");
		String endereco3 = sc.next();
		System.out.println("");
		System.out.print("Digite o seu código: ");
		String codigo4 = sc.next();
		System.out.print("Digite o seu nome: ");
		String nome4 = sc.next();
		System.out.print("Digite seu sexo: ");
		String sexo4 = sc.next();
		System.out.print("Digite sua data de nascimento: ");
		String data4 = sc.next();
		System.out.print("Digite seu e-mail: ");
		String email4 = sc.next();
		System.out.print("Digite seu telefone/celular: ");
		String cel4 = sc.next();
		System.out.print("Digite seu CPF: ");
		String cpf4 = sc.next();
		System.out.print("Digite seu endereço: ");
		String endereco4 = sc.next();
		System.out.println("");
		System.out.print("Digite o seu código: ");
		String codigo5 = sc.next();
		System.out.print("Digite o seu nome: ");
		String nome5 = sc.next();
		System.out.print("Digite seu sexo: ");
		String sexo5 = sc.next();
		System.out.print("Digite sua data de nascimento: ");
		String data5 = sc.next();
		System.out.print("Digite seu e-mail: ");
		String email5 = sc.next();
		System.out.print("Digite seu telefone/celular: ");
		String cel5 = sc.next();
		System.out.print("Digite seu CPF: ");
		String cpf5 = sc.next();
		System.out.print("Digite seu endereço: ");
		String endereco5 = sc.next();
		System.out.println("");
		System.out.println("****CLIENTE 1****");
		System.out.println("Seu código: " + codigo1);
		System.out.println("Seu nome: " + nome1);
		System.out.println("Seu sexo: " + sexo1);
		System.out.println("Sua data de nascimento: " + data1);
		System.out.println("Seu e-mail: " + email1);
		System.out.println("Seu Telefone/celular: " + cel1);
		System.out.println("Seu cpf: " + cpf1);
		System.out.println("Seu endereço: " + endereco1);
		System.out.println("");
		System.out.println("****CLIENTE 2****");
		System.out.println("Seu código: " + codigo2);
		System.out.println("Seu nome: " + nome2);
		System.out.println("Seu sexo: " + sexo2);
		System.out.println("Sua data de nascimento: " + data2);
		System.out.println("Seu e-mail: " + email2);
		System.out.println("Seu Telefone/celular: " + cel2);
		System.out.println("Seu cpf: " + cpf2);
		System.out.println("Seu endereço: " + endereco2);
		System.out.println("");
		System.out.println("****CLIENTE 3****");
		System.out.println("Seu código: " + codigo3);
		System.out.println("Seu nome: " + nome3);
		System.out.println("Seu sexo: " + sexo3);
		System.out.println("Sua data de nascimento: " + data3);
		System.out.println("Seu e-mail: " + email3);
		System.out.println("Seu Telefone/celular: " + cel3);
		System.out.println("Seu cpf: " + cpf3);
		System.out.println("Seu endereço: " + endereco3);
		System.out.println("");
		System.out.println("****CLIENTE 4****");
		System.out.println("Seu código: " + codigo4);
		System.out.println("Seu nome: " + nome4);
		System.out.println("Seu sexo: " + sexo4);
		System.out.println("Sua data de nascimento: " + data4);
		System.out.println("Seu e-mail: " + email4);
		System.out.println("Seu Telefone/celular: " + cel4);
		System.out.println("Seu cpf: " + cpf4);
		System.out.println("Seu endereço: " + endereco4);
		System.out.println("");
		System.out.println("****CLIENTE 5****");
		System.out.println("Seu código: " + codigo5);
		System.out.println("Seu nome: " + nome5);
		System.out.println("Seu sexo: " + sexo5);
		System.out.println("Sua data de nascimento: " + data5);
		System.out.println("Seu e-mail: " + email5);
		System.out.println("Seu Telefone/celular: " + cel5);
		System.out.println("Seu cpf: " + cpf5);
		System.out.println("Seu endereço: " + endereco5);

		sc.close();
	}

}